services:
  sql_server_ip:
  sql_server_username:
  sql_server_password:


config:
  SQLALCHEMY_DATABASE_URI: "sqlite:///lib/tbot.db"
  subscribers_file: "subscribers.csv"
  file_name: "lib/tbot.db"
  twitch_username:
  twitch_api: